language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t andremiranda/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true andremiranda/react-test npm test

after_success:
  - docker build -t andremiranda/multi-client ./client
  - docker build -t andremiranda/multi-nginx ./nginx
  - docker build -t andremiranda/multi-worker ./worker
  - docker build -t andremiranda/multi-server ./server
  # Docker log in
  - echo "$DOCKER_PASSWORD" |  docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and pull them to docker hub
  - docker push andremiranda/multi-client
  - docker push andremiranda/multi-nginx
  - docker push andremiranda/multi-worker
  - docker push andremiranda/multi-server

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-172733370974
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
